name: Tablist
main: de.firelort.tablist.Tablist
author: firelort
version: 2
permissions:
  tablist.rank1:
    description: Rechte für den ersten Prefix.
  tablist.rank2:
    description: Rechte für den zweiten Prefix.
  tablist.rank3:
    description: Rechte für den dritten Prefix.
  tablist.rank4:
    description: Rechte für den vierten Prefix.
  tablist.rank5:
    description: Rechte für den fünften Prefix.
  tablist.rank6:
    description: Rechte für den sechsten Prefix.
  tablist.rank7:
    description: Rechte für den siebten Prefix.
  tablist.rank8:
    description: Rechte für den achten Prefix.
  tablist.rank9:
    description: Rechte für den neunten Prefix.
  tablist.rank10:
    description: Rechte für den zehnten Prefix.
  tablist.rank11:
    description: Rechte für den elften Prefix.
  tablist.rank12:
    description: Rechte für den zwölften Prefix.
  tablist.rank13:
    description: Rechte für den dreizehnten Prefix.
  tablist.rank14:
    description: Rechte für den vierzehnten Prefix.
  tablist.rank15:
    description: Rechte für den fünfzehnten Prefix.